# Generated by Django 5.2.7 on 2025-10-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carboncredit',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Crédito verificado por administrador'),
        ),
    ]
