# Generated by Django 5.2.7 on 2025-10-30 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_carboncredit_is_verified'),
        ('transactions', '0002_alter_transaction_options_alter_transaction_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carboncredit',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete - crédito imutável'),
        ),
        migrations.CreateModel(
            name='CreditOwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('CREATION', 'Credit Created'), ('SALE', 'Sold'), ('TRANSFER', 'Transferred')], max_length=16)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço pago na transferência (se aplicável)', max_digits=12, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='credits.carboncredit')),
                ('from_owner', models.ForeignKey(blank=True, help_text='Null para criação inicial', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits_transferred_from', to=settings.AUTH_USER_MODEL)),
                ('to_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits_transferred_to', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ownership_records', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Histórico de Propriedade',
                'verbose_name_plural': 'Históricos de Propriedade',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['credit', 'timestamp'], name='credits_cre_credit__16a8cb_idx')],
            },
        ),
    ]
