# Generated by Django 5.2.7 on 2025-10-30 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_carboncredit_is_deleted_creditownershiphistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carboncredit',
            name='auditor_notes',
            field=models.TextField(blank=True, help_text='Observações do auditor sobre a validação'),
        ),
        migrations.AddField(
            model_name='carboncredit',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='Data da validação', null=True),
        ),
        migrations.AddField(
            model_name='carboncredit',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Auditor que validou o crédito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carboncredit',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Aguardando Validação'), ('UNDER_REVIEW', 'Em Análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', help_text='Status de validação pelo auditor', max_length=20),
        ),
    ]
