# Generated by Django 5.2.7 on 2025-10-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_carboncredit_is_deleted_creditownershiphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='carboncredit',
            name='auditor_notes',
            field=models.TextField(blank=True, default='', help_text='Notas do auditor sobre a validação do crédito'),
        ),
    ]
