# Generated by Django 5.2.7 on 2025-10-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo virtual para compra de créditos (R$)', max_digits=12),
        ),
    ]
