# Generated by Django 5.2.7 on 2025-10-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PRODUCER', 'Produtor'), ('COMPANY', 'Empresa'), ('ADMIN', 'Administrador')], default='COMPANY', max_length=20),
        ),
    ]
