# Generated by Django 5.2.7 on 2025-10-30 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PRODUCER', 'Produtor'), ('COMPANY', 'Empresa'), ('AUDITOR', 'Auditor'), ('ADMIN', 'Administrador')], default='COMPANY', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(help_text='Explique sua experiência e qualificações para ser auditor', verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Candidatura')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Revisão')),
                ('rejection_reason', models.TextField(blank=True, help_text='Explique o motivo da rejeição (opcional)', verbose_name='Motivo da Rejeição')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_applications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Candidatura de Auditor',
                'verbose_name_plural': 'Candidaturas de Auditores',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user',), name='unique_pending_application_per_user')],
            },
        ),
    ]
