# Generated by Django 5.2.7 on 2025-10-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_auditorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorapplication',
            name='certificate',
            field=models.FileField(blank=True, help_text='Certificado de qualificação (PDF ou imagem)', upload_to='auditor_applications/certificates/%Y/%m/', verbose_name='Certificado'),
        ),
        migrations.AddField(
            model_name='auditorapplication',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='auditorapplication',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='auditorapplication',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='URL do perfil do LinkedIn', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='auditorapplication',
            name='organization',
            field=models.CharField(blank=True, help_text='Empresa ou autônomo', max_length=255, verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='auditorapplication',
            name='phone',
            field=models.CharField(blank=True, help_text='Formato: (XX) XXXXX-XXXX', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='auditorapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Currículo em PDF (opcional)', upload_to='auditor_applications/resumes/%Y/%m/', verbose_name='Currículo'),
        ),
        migrations.AddField(
            model_name='auditorapplication',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Li e aceito os termos de auditoria', verbose_name='Aceite dos Termos'),
        ),
        migrations.AlterField(
            model_name='auditorapplication',
            name='justification',
            field=models.TextField(help_text='Por que você quer ser um auditor na EcoTrade?', verbose_name='Motivação'),
        ),
    ]
