# Generated by Django 5.2.7 on 2025-10-31 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_approved_at_alter_user_role_auditorprofile_and_more'),
        ('accounts', '0005_auditorapplication_certificate_and_more'),
    ]

    operations = [
    ]
