# Generated by Django 5.2.7 on 2025-10-31 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20251031_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approved_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PRODUCER', 'Produtor'), ('COMPANY', 'Empresa'), ('AUDITOR', 'Auditor'), ('ADMIN', 'Administrador')], default='COMPANY', max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('farm_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Saldo virtual para compra de créditos (R$)', max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
